name: Build ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl wget openjdk-11-jdk python3 python3-pip unzip
        sudo curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo
        sudo chmod a+rx /usr/local/bin/repo

    - name: Clonar repositório da ROM
      run: |
        mkdir rom
        cd rom
        repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
        repo sync -c --no-clone-bundle --no-tags --force-sync -j4

    - name: Compilar ROM
      run: |
        set -e
        cd rom
        source build/envsetup.sh
        lunch lineage_cebu-userdebug
        make bacon -j4
