name: Construir ROM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Instalar dependências
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl wget openjdk-17-jdk python3 python3-pip unzip bc bison build-essential ccache clang flex g++-multilib gcc-multilib libncurses5-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

        sudo curl https://storage.googleapis.com/git-repo-downloads/repo > repo
        chmod a+rx repo
        sudo mv repo /usr/local/bin/repo

    - name: Clonar repositório da ROM
      run: |
        mkdir rom
        cd rom
        repo init -u https://github.com/LineageOS/android.git -b lineage-22.2
        repo sync -c --no-clone-bundle --no-tags --force-sync -j4

    - name: Compilar a ROM
      run: |
        set -e
        cd rom
        source build/envsetup.sh
        lunch lineage_cebu-userdebug
        make bacon -j$(nproc)
